import { readFile } from 'fs/promises';
import { basename } from 'path';
import config from '../../config/default.js';
import logger from '../utils/logger.js';
import { translateCaption } from '../translator/gemini.js';
import Zernio from '@zernio/node';

/**
 * Upload a video to TikTok using the Zernio API via @zernio/node SDK.
 * 
 * Flow:
 * 1. Get presigned URL from Zernio
 * 2. Upload the .mp4 file to the cloud storage bucket
 * 3. Translate and optimize caption using Gemini AI.
 * 4. Create a post in Zernio using the public URL and translated caption.
 *
 * @param {string} videoPath - Path to the output .mp4 video
 * @param {object} rawCaptionData - Raw caption JSON data generated by the pipeline
 * @param {boolean} [isDraft=false] - If true, uploads to TikTok as a draft instead of publishing
 * @returns {Promise<{success: boolean, postId?: string, error?: string}>}
 */
export async function uploadToTikTok(videoPath, rawCaptionData, isDraft = false) {
  const apiKey = config.zernio.apiKey;

  if (!apiKey) {
    throw new Error('ZERNIO_API_KEY is not set in .env');
  }

  const zernio = new Zernio({ apiKey });

  try {
    logger.info(`Starting Zernio upload for: ${basename(videoPath)}`);

    // ── Step 1: Upload Media (Two-Step Presigned URL) ──
    logger.info('Requesting presigned upload URL from Zernio...');

    // Read file into buffer
    const buffer = await readFile(videoPath);
    const filename = basename(videoPath);
    const contentType = 'video/mp4';

    // 1a. Get presigned URL via SDK
    const { data: presignResult } = await zernio.media.getMediaPresignedUrl({
      body: {
        filename: filename,
        contentType: contentType
      }
    });

    const uploadUrl = presignResult.uploadUrl || presignResult.upload_url || presignResult.url;
    const mediaId = presignResult.key || presignResult.id || presignResult.media_id;
    const publicUrl = presignResult.publicUrl || presignResult.public_url;

    if (!uploadUrl || (!mediaId && !publicUrl)) {
      throw new Error(`Invalid presign response: ${JSON.stringify(presignResult)}`);
    }

    // 1b. Upload directly to the presigned URL (S3/Cloudinary/etc) using native fetch
    logger.info('Uploading video data to cloud storage...');
    const uploadResponse = await fetch(uploadUrl, {
      method: 'PUT',
      headers: {
        'Content-Type': contentType
      },
      body: buffer
    });

    if (!uploadResponse.ok) {
      const errorText = await uploadResponse.text();
      throw new Error(`Cloud upload failed (${uploadResponse.status}): ${errorText}`);
    }

    logger.success(`Media uploaded successfully. Media ID: ${mediaId}`);

    // ── Step 2: Translate Caption ──
    logger.info('Translating and optimizing video caption/tags...');
    const translatedData = await translateCaption(rawCaptionData);

    // ── Step 3: Create Post ──
    logger.info(`Creating TikTok post via Zernio SDK (Draft: ${isDraft})...`);

    // Construct the final caption: description + hashtags
    const hashtags = (translatedData.tags || [])
      .map(tag => `#${tag}`)
      .join(' ');

    const finalCaption = `${translatedData.title}\n\n${translatedData.desc}\n\n${hashtags}`;

    // Zernio payload structure based on SDK spec
    const postPayload = {
      title: translatedData.title,
      content: finalCaption,
      mediaItems: [
        {
          type: 'video',
          url: publicUrl || mediaId,
          title: translatedData.title
        }
      ],
      platforms: [
        {
          platform: 'tiktok',
          accountId: config.zernio.tiktokAccountId
        }
      ]
    };

    if (isDraft) {
      postPayload.tiktokSettings = { draft: true };
    } else {
      postPayload.publishNow = true;
    }

    const { data: postResult } = await zernio.posts.createPost({
      body: postPayload
    });

    logger.success('✅ TikTok post scheduled/published successfully via Zernio!');

    return {
      success: true,
      postId: postResult.id || postResult.post_id,
      mediaId
    };

  } catch (err) {
    logger.error(`Zernio upload failed: ${err.message}`);
    return {
      success: false,
      error: err.message
    };
  }
}

export default { uploadToTikTok };
